const FETCH_MESSAGE = 'FETCH_MESSAGE';
const FETCH_MESSAGEAF = 'FETCH_MESSAGE';
const LOGIN = 'LOGIN';
const LOGOUT = 'LOGOUT';
const CLEAR_MESSAGE = 'CLEAR_MESSAGEAF';
const CLEAR_MESSAGEAF = 'CLEAR_MESSAGEAF';
export {
  FETCH_MESSAGE,
  FETCH_MESSAGEAF,
  LOGIN,
  LOGOUT,
  CLEAR_MESSAGE,
  CLEAR_MESSAGEAF,
};
