const GET_MESSAGE_LIST = 'GET_MESSAGE_LIST';
const GET_MESSAGE_LOADING = 'GET_MESSAGE_LOADING';
const GET_MESSAGE_ERROR = 'GET_MESSAGE_ERROR';
const GET_CURRENT_USER = 'GET_CURRENT_USER';
const GET_CURRENT_USER_LOADING = 'GET_CURRENT_USER_LOADING';
const GET_CURRENT_USER_TOKEN = 'GET_CURRENT_USER_TOKEN';
const GET_CURRENT_USER_ADMIN_STATUS = 'GET_CURRENT_USER_ADMIN_STATUS';
const GET_CURRENT_USER_STATUS ='GET_CURRENT_USER_STATUS';
const GET_MESSAGEAF_LIST = 'GET_MESSAGEAF_LIST';
const GET_MESSAGEAF_LOADING = 'GET_MESSAGEAF_LOADING';
const GET_MESSAGEAF_ERROR = 'GET_MESSAGEAF_ERROR';

export {
  GET_MESSAGE_LIST,
  GET_MESSAGE_LOADING,
  GET_MESSAGE_ERROR,
  GET_CURRENT_USER,
  GET_CURRENT_USER_LOADING,
  GET_CURRENT_USER_TOKEN,
  GET_CURRENT_USER_ADMIN_STATUS,
  GET_CURRENT_USER_STATUS,
  GET_MESSAGEAF_LIST,
  GET_MESSAGEAF_LOADING,
  GET_MESSAGEAF_ERROR,
};
