const SET_MESSAGE_LIST = 'SET_MESSAGE_LIST';
const SET_MESSAGE_LOADING = 'SET_MESSAGE_LOADING';
const SET_MESSAGE_ERROR = 'SET_MESSAGE_ERROR';
const SET_CURRENT_USER = 'SET_CURRENT_USER';
const SET_CURRENT_USER_LOADING = 'SET_CURRENT_USER_LOADING';
const SET_CURRENT_STATUS ='SET_CURRENT_STATUS';
const SET_MESSAGEAF_LIST = 'SET_MESSAGEAF_LIST';
const SET_MESSAGEAF_LOADING = 'SET_MESSAGEAF_LOADING';
const SET_MESSAGEAF_ERROR = 'SET_MESSAGEAF_ERROR';

export {
  SET_MESSAGE_LIST,
  SET_MESSAGE_LOADING,
  SET_MESSAGE_ERROR,
  SET_CURRENT_USER,
  SET_CURRENT_USER_LOADING,
  SET_CURRENT_STATUS,
  SET_MESSAGEAF_LIST,
  SET_MESSAGEAF_LOADING,
  SET_MESSAGEAF_ERROR,
};
